
name: 'sf_fire_incidents'
version: '1.0.0'
config-version: 2

profile: 'sf_fire_incidents'

model-paths: ["models"]
test-paths: ["tests"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  sf_fire_incidents:
    staging:
      load:
        +materialized: table
        +schema: raw
      +materialized: view
      +schema: staging
    marts:
      core:
        +materialized: table
        +schema: core
      business_intelligence:
        +materialized: incremental
        +schema: bi