version: 2

models:
  - name: incidents_by_time
    description: "Monthly incident trends with YoY comparisons"
    columns:
      - name: incident_date_month
        description: "First day of the month for aggregation"
        tests:
          - not_null
      - name: total_property_loss
        description: "Sum of estimated property damage"
        tests:
          - relationships:
              to: ref('fact_fire_incidents')
              field: estimated_property_loss
              severity: warn

  - name: incidents_by_district
    description: "Incident metrics grouped by supervisor district"
    columns:
      - name: district_code
        tests:
          - accepted_values:
              values: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11']